### ISSUE TITLE
New icons are not updated

### ISSUE THREAD

**Issue by brigazvi** [elementary/appcenter-web#23]
I designed new logos for [ValaCompiler ](https://github.com/BharatKalluri/Gifup/pull/41/files?short_path=750a8ee#diff-750a8ee5a5e524e8fa455a87f342a8a7)and [Gifup](https://github.com/basjam/ValaCompiler/pull/32/files?short_path=0df9d7d#diff-0df9d7d466063cb52ac2e8f74b856c41).
The designs have been updated in app repositories.
On the site, the old logos still appear.

**Comment by cassidyjames** [comment]
@brigazvi I have to get automatic rebuilding of the repo working again, and then the new icons should roll out within 24 hours of the update being pushed to users.

**Comment by cassidyjames** [comment]
@brigazvi I think what might be happening now is that the Juno version has the new icons, but the site currently prioritizes the Loki versions. I have an issue to correct that at #21.
