### ISSUE TITLE
No icon when an app doesn't have any screenshots

### ISSUE THREAD

**Issue by gamerlv** [elementary/appcenter-web#4]
Currently, when an app does not have any screenshots listed it is not possible to get their _release hash_. This makes it hard to create a correct icon URL, even if the app does have AppSteam icons.

**Comment by cassidyjames** [comment]
This is resolved in `main` since we enforce screenshots in Hera and newer, and since the Flatpak remote doesn't rely on the same baseUrl stuff as before.
