### ISSUE TITLE
Reconsider calls to action on app detail pages

### ISSUE THREAD

**Issue by ryanprior** [elementary/appcenter-web#43]
The calls to action on AppCenter app detail pages are weak.

Up top, we have an extremely prominent call to action: "Get elementary OS"

>![call to action top](https://user-images.githubusercontent.com/4389854/61101571-e4c45100-a42f-11e9-90d1-1581047d0a3c.png)

This is not helpful. Let's consider a few user stories:
* I'm a non-Elementary user here to read about an app. I don't understand the relationship between Elementary and the AppCenter yet, so the CTA goes right over my head.
* I'm an Elementary user browsing on a non-Elementary secondary device. I don't intend to install Elementary on this device, so the CTA is irrelevant to me.
* I'm an Elementary user browsing apps that I might want to install on this device right now. The CTA is irrelevant to me.
* I'm a non-Elementary user desperate to install an app from the AppCenter. I am highly motivated and will do practically anything asked of me to make this happen. I have a spare laptop, a big flash drive, plenty of network bandwidth, and plenty of spare time to install a new OS in order to accomplish my goal. Ding ding ding! I'm the only user who's served well by this CTA.

Further down, we have another call to action: "Get it for $20 on AppCenter."

>![call to action](https://user-images.githubusercontent.com/4389854/61101814-daef1d80-a430-11e9-95d6-a22f795eb128.png)

The sentiment is great, but there's literally no mechanism provided to assist the user in doing what we ask. Where's the "Open in App Center" button we're so pushy with when a user first navigates to the app detail page?

Another, de-emphasized call to action coupled with this is "publish to AppCenter." Why is this under the heading "Get it for $20 on AppCenter?" This seems to deserve its own sub-heading and a more prominent CTA, since the page referenced by that link is actually super clear and helpful for its target audience. But we have no reason to think that they'll scroll down the page and look for this nearly-hidden, non-clickable-looking CTA under this irrelevant heading.

**Comment by ryanprior** [comment]
I had a thought just now, looking at @bradleytaunt's mockup in #44: what if we replaced the text "Get elementary OS" with "Available on elementary OS" and made it look like a [ghost button](https://designmodo.com/ghost-buttons/) instead of a pushbutton?

I think the change would have these benefits:
* communicates to people who are already using elementary OS that this app is available to them 
* educates people who aren't using eos about what they'd have to do in order to get the app
* reduces the visual weight of the button, allowing nearby content like app icons to stand out

**Comment by cassidyjames** [comment]
This will necessarily be resolved with #62, but I'll leave it open until that work is done.

**Comment by cassidyjames** [comment]
Closed by #69
