### ISSUE TITLE
Loki apps should not be displayed any longer.

### ISSUE THREAD

**Issue by bigfatbird** [elementary/appcenter-web#47]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
A list of old apps currently not available shows on the bottom of the homepage.
Since Juno is out and even surpassed by Hera we should consider burying them. Patient is dead, Jim.

### To Reproduce
1. Go to 'appcenter.elementary.io'
2. Scroll down to 'bottom of the homepage'
3. There is a greyed out list of old apps not available to Hera.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ X] I'm using the latest released stable version

**Comment by cassidyjames** [comment]
I've more clearly distinguished them in c0f24a50102e36b4e4eb0132262c078802a69ecb at least for now. But I could probably be convinced that we should drop them altogether. The one downside of that is that our count of apps will look like it goes down.

**Comment by bigfatbird** [comment]
I like this solution. While I still think that the current counter is a "lie" already, if you count all apps that were ever written for elementary OS, but are not anymore available to install on a supported OS i can live with that solution for the moment.
