### ISSUE TITLE
Daily builds aren't running

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter-web#54]
Something seems to have broken :grimacing:

**Comment by ryonakano** [comment]
Travis seems to complain about missing credits:

![スクリーンショット 2021-08-07 8 21 18](https://user-images.githubusercontent.com/26003928/128579540-0288cc20-f88a-4a08-9a92-2f7030c7a6b7.png)

**Comment by cassidyjames** [comment]
I've fixed this in `main` by moving to a GitHub Action! This site _might_ not be long for this world if we switch over to https://github.com/flathub/linux-store-frontend, but at least it should be working again for now.
