### ISSUE TITLE
Include apps from Flatpak remote

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter-web#57]
We should be able to add a new Ruby script or similar which pulls this down and parses it like we do for `loki` and `hera`:

http://flatpak.elementary.io/repo/appstream/x86_64/appstream.xml.gz

The big difference is that this is XML instead of YAML so it's not just a drop-in. :sweat_smile:

**Comment by RMcNeely** [comment]
With the change to Flatpak I assume that XML will be the standard for releases moving forward?

**Comment by cassidyjames** [comment]
@RMcNeely correct. We'll likely want to keep the loki/hera data around for now for historical purposes, but that format is legacy.

**Comment by ChildishGiant** [comment]
I currently can't link people to my app because of this :cry:

**Comment by RMcNeely** [comment]
> I currently can't link people to my app because of this

Which app is yours thats not displaying?

**Comment by ChildishGiant** [comment]
https://appcenter.elementary.io/com.github.childishgiant.mixer I didn't have a release before Odin so there's no deb version to show
