### ISSUE TITLE
Homepage, License, Send Feedback etc missing

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/appcenter-web#71]
![image](https://user-images.githubusercontent.com/13716824/130147930-556b2568-5c6e-4a51-bd0f-fef8283b15f1.png)
This is very useful for opening up the source on github etc

**Comment by cassidyjames** [comment]
I see the issue here, thanks for reporting!

**Comment by cassidyjames** [comment]
Fixed in b753f562939992a98d7ba966c6c0469e1a7197e5
