### ISSUE TITLE
com.github.matthiasjg.trimirjournal not listed on appcenter-web and detail page broken  

### ISSUE THREAD

**Issue by matthiasjg** [elementary/appcenter-web#82]
### What Happened?

Coming here from https://github.com/elementary/appcenter-reviews/pull/253

My app `com.github.matthiasjg.trimirjournal` is not listed on the appcenter's web page. It actually never was, though I'm a few releases in.

In addition I noticed, that the [app's detail page](https://appcenter.elementary.io/com.github.matthiasjg.trimirjournal/
) is somehow broken: no `</developer_name>` in header, no screenshots, wrong colors, etc.

Is this because I do something wrong, maybe in my `appdata.xml`?
If so a pointer would be much appreciated. Thank you.

### Steps to Reproduce

1. go to https://appcenter.elementary.io/ and search for **Trimir Journal** — no hits
2. go to https://appcenter.elementary.io/com.github.matthiasjg.trimirjournal/ — no `</developer_name>` in header, no screenshots, wrong colors, etc.

### Expected Behavior

1. app is listed on appcenter web
2. app's detail page reflects data from app's `appdata.xml`

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by cassidyjames** [comment]
It looks like the quotes are not being escaped properly, and are thus breaking the page.

**Comment by cassidyjames** [comment]
Fixed in 71c640e9f56e3685c5bb29870753eacb750f7b4e
